/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.busbooking.ui;

/**
 *
 * @author YOGARAJ
 */
public class SeatSelectionFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeatSelectionFrame.class.getName());
String selectedSeat="";
    /**
     * Creates new form SeatSelectionFrame
     */
    public SeatSelectionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnA1 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Your Seat");

        btnA1.setText("A1");
        btnA1.addActionListener(this::btnA1ActionPerformed);

        btnA2.setText("A2");
        btnA2.addActionListener(this::btnA2ActionPerformed);

        btnA3.setText("A3");
        btnA3.addActionListener(this::btnA3ActionPerformed);

        btnA4.setText("A4");
        btnA4.addActionListener(this::btnA4ActionPerformed);

        btnB1.setText("B1");
        btnB1.addActionListener(this::btnB1ActionPerformed);

        btnB2.setText("B2");
        btnB2.addActionListener(this::btnB2ActionPerformed);

        btnB3.setText("B3");
        btnB3.addActionListener(this::btnB3ActionPerformed);

        btnB4.setText("B4");
        btnB4.addActionListener(this::btnB4ActionPerformed);

        btnC1.setText("C1");
        btnC1.addActionListener(this::btnC1ActionPerformed);

        btnC2.setText("C2");
        btnC2.addActionListener(this::btnC2ActionPerformed);

        btnC3.setText("C3");
        btnC3.addActionListener(this::btnC3ActionPerformed);

        btnC4.setText("C4");
        btnC4.addActionListener(this::btnC4ActionPerformed);

        btnConfirm.setText("Confirm Booking");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnB1)
                                .addGap(18, 18, 18)
                                .addComponent(btnB2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnA1)
                                .addGap(18, 18, 18)
                                .addComponent(btnA2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnB3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnC3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnB4)
                                    .addComponent(btnC4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnA3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnA4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnC1)
                        .addGap(18, 18, 18)
                        .addComponent(btnC2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnConfirm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA1)
                    .addComponent(btnA2)
                    .addComponent(btnA3)
                    .addComponent(btnA4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnB1)
                    .addComponent(btnB2)
                    .addComponent(btnB3)
                    .addComponent(btnB4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC1)
                    .addComponent(btnC2)
                    .addComponent(btnC3)
                    .addComponent(btnC4))
                .addGap(31, 31, 31)
                .addComponent(btnConfirm)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1ActionPerformed
selectedSeat="B1";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat B1 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnB1ActionPerformed

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
selectedSeat="A1";
btnA1.setBackground(java.awt.Color.GREEN);
    javax.swing.JOptionPane.showMessageDialog(this,
            "Seat A1 Selected");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
      selectedSeat="A2";
btnA1.setBackground(java.awt.Color.RED); 
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat A2 Selected"); // TODO add your handling code here:
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
selectedSeat="A3";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat A3 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed

        selectedSeat="A4";
btnA1.setBackground(java.awt.Color.GREEN);
javax.swing.JOptionPane.showMessageDialog(this,
            "Seat A4 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
selectedSeat="B2";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat B2 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnB2ActionPerformed

    private void btnB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB3ActionPerformed
selectedSeat="B3";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat B3 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnB3ActionPerformed

    private void btnB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB4ActionPerformed
selectedSeat="B4";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat B4 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnB4ActionPerformed

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
selectedSeat="C1";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat C1 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
selectedSeat="C2";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat C2 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
selectedSeat="C3";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat C3 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btnC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC4ActionPerformed
selectedSeat="C4";
btnA1.setBackground(java.awt.Color.GREEN);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seat C4 Selected");        // TODO add your handling code here:
    }//GEN-LAST:event_btnC4ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

    
    

    if(selectedSeat.equals("")){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a seat first");
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(this,
            "Booking Confirmed!\nSeat: " + selectedSeat);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SeatSelectionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC4;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
